-- Tabela PROJETO
CREATE TABLE PROJETO (
    Projnumero INT CHECK (Projnumero BETWEEN 1 AND 2000),
    Projlocal INT CHECK (Projlocal BETWEEN 1 AND 200),
    Dnum INT CHECK (Dnum BETWEEN 1 AND 50),
    PRIMARY KEY (Projnumero)
);

-- Tabela DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    Dnumero INT CHECK (Dnumero BETWEEN 1 AND 50),
    Cpf_ger INT CHECK (Cpf_ger BETWEEN 1 AND 50),
    PRIMARY KEY (Dnumero)
);

-- Tabela FUNCIONARIO
CREATE TABLE FUNCIONARIO (
    Cpf INT CHECK (Cpf BETWEEN 1 AND 10000),
    Dnr INT CHECK (Dnr BETWEEN 1 AND 50),
    Salario INT CHECK (Salario BETWEEN 1 AND 500),
    PRIMARY KEY (Cpf)
);

-- Índice PROJ_PLOC
CREATE INDEX PROJ_PLOC ON PROJETO (Projlocal);

-- Índice CPF_FUNC
CREATE UNIQUE INDEX CPF_FUNC ON FUNCIONARIO (Cpf);

-- Índice SAL_FUNC
CREATE INDEX SAL_FUNC ON FUNCIONARIO (Salario);